name: Super-Linter with Node.js

on: workflow_dispatch

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Specify the Node.js version you need

      - name: Install Node.js dependencies
        run: |
          npm install # Install any necessary Node.js dependencies

      - name: Run Custom Node.js Script
        run: |
          node ${{ github.workspace }}/custom_script.js

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
